### ISSUE TITLE
"ImportError: No module named utils" when running ./prep/prep_narrativeqa.py

### ISSUE THREAD

**Issue by TianboJi** [vanzytay/NIPS2018_DECAPROP#1]
This error looks like that it lacks a file named "utils.py". Could you please help to fix it?

**Comment by TianboJi** [comment]
Now the utils module works fine, but "nus_utilities" and "common_v2" are still unavailable. Could you please upload it? Thank you.

**Comment by vanzytay** [comment]
Will push it on the next update

**Comment by DbrRoxane** [comment]
Hi, has it been pushed? I still have the same error here
