### ISSUE TITLE
Modules missing in tylib/lib folder and Missing Functions

### ISSUE THREAD

**Issue by vjg28** [vanzytay/NIPS2018_DECAPROP#3]
Apart from the last issue problem mentioned (that need some serious attention), there are a number of modules and functions missing. Some of the notable are 
- `tylib/lib/complex_op`
- `tylib/lib/enhanced`
- `tylib/lib/qrnn`
- `tylib/lib/bimpm`
- `tylib/lib/stat`
- `tylib/lib/opt`
- `tylib/lib/loss`

I commented them all which were missing and still it resulted in a number of undefined functions. I guess maybe some of these functions will be in the missing modules. @vanzytay, please do look into this and provide the complete code.

**Comment by doudouzqx** [comment]
I met the same problems,have you resolved these?

**Comment by vjg28** [comment]
@doudouzqx No. The missing files are not required in the code, but there is still an issue of undefined modules. Especially the intra-attention module. I tried solving it myself, but it didn't work. You could check it [here](https://github.com/vjg28/NLP_RL). I removed as many errors as I could. But it is still not operational.

**Comment by vanzytay** [comment]
@vjg28 Codebase is copied from my main infrastructure so there are missing things everywhere. Free free to use whatever is useful for you here. The ideal use case is to use the model code for reference and use your own infrastructure. This repository is not maintained. :)
