### ISSUE TITLE
Result obtained from the code aren't as described in the paper.

### ISSUE THREAD

**Issue by 11meghna** [vanzytay/NIPS2018_DECAPROP#5]
I have tried removing the errors, and after running the code I got the results as follows
Bleu1=4.75277632252139
[max] Bleu4=0.0002252375950162494
[max] Meteor=2.725085966130152
[max] Rouge=20.281084140962612

Kindly help me out with this.

**Comment by vanzytay** [comment]
You have to tune the hyperparameters. the default hparams in this repo are probably far from what we used. try following the hparams in paper closely.
